update for latest dorothy conventions
/ref https://github.com/bevry/dorothy/pull/250
/ref https://github.com/bevry/dorothy/commit/7ee7f6c1873c2ccb8e9e6d6f46f2c26f901c21a1

diff --git a/commands/boundation-upgrade b/commands/boundation-upgrade
--- a/commands/boundation-upgrade
+++ b/commands/boundation-upgrade
@@ -24,16 +24,17 @@ function boundation_upgrade() (
 			fi
 		fi
 		__print_line
-		__print_line "$message"
+		__print_lines "$message"
 	}
 	trap on_finish EXIT
 
 	# helpers
 	function get_node_engine {
-		grep --after-context=1 --fixed-strings --regexp='engines' <package.json |
-			grep --fixed-strings --regexp='node' |
-			head -n1 |
-			xargs
+		jq -r '.engines.node' package.json
+		# grep --after-context=1 --fixed-strings --regexp='engines' <package.json |
+		# 	grep --fixed-strings --regexp='node' |
+		# 	head -n1 |
+		# 	xargs
 	}
 	function get_node_license {
 		jq -r '.license' package.json
@@ -45,15 +46,15 @@ function boundation_upgrade() (
 	lo="$(get_node_license)"
 
 	# install global deps
-	if ! command-exists boundation; then
+	if ! command-exists -- boundation; then
 		echo-style --bold='installing' ' ' --code='boundation'
 		nvm-env -- npm i -g boundation
 	fi
-	if ! command-exists github-backers; then
+	if ! command-exists -- github-backers; then
 		echo-style --bold='installing' ' ' --code='github-backers'
 		nvm-env -- npm i -g '@bevry/github-api'
 	fi
-	if ! command-exists make-deno-edition; then
+	if ! command-exists -- make-deno-edition; then
 		echo-style --bold='installing' ' ' --code='make-deno-edition'
 		nvm-env -- npm i -g make-deno-edition
 	fi
@@ -159,7 +160,7 @@ function boundation_upgrade() (
 	git add .
 	git commit -am "$v - boundation, changelog, version bump"
 	# if ! nvm-env -- npm owner add bevryme; then
-	# 	__print_line 'adding npm owner failed, trying again in two minutes'
+	# 	__print_lines 'adding npm owner failed, trying again in two minutes'
 	# 	sleep 2m
 	# 	nvm-env -- npm owner add bevryme
 	# fi
diff --git a/commands/magnet-search b/commands/magnet-search
--- a/commands/magnet-search
+++ b/commands/magnet-search
@@ -35,7 +35,6 @@ function magnet_search() (
 	__require_array 'mapfile'
 
 	# dependencies
-	source "$DOROTHY/sources/ripgrep.bash"
 	setup-util --quiet --cli='attractorr' \
 		CARGO='--git https://github.com/rnestler/attractorr'
 	setup-util --quiet --cli='magnetfinder' \
@@ -46,12 +45,13 @@ function magnet_search() (
 	mapfile -t lines < <(attractorr --sort=seeders "$search" 2>&1 || :)
 	for line in "${lines[@]}"; do
 		line="$(echo-trim-colors -- "$line")"
-		if test -z "$line" || rg --quiet --regexp='ERROR|No results|btih:000000000000' <<<"$line"; then
+		if test -z "$line" || echo-regexp -q --regexp='ERROR|No results|btih:000000000000' -- "$line"; then
 			continue
 		fi
-		__print_line "$line"
+		__print_lines "$line"
 	done
 
+	source "$DOROTHY/sources/ripgrep.bash"
 	mapfile -t lines < <(magnetfinder --no-interactive --show 5 -aq "$search" 2>/dev/null | rg --invert-match --fixed-strings --regexp='No torrents found matching search query' || :)
 	echo-split $'\t' -- "${lines[@]}"
 )
