utilise the upcoming dorothy conventions
- `boundation-all`, `config-sync`, `stig-rm-duplicates`:
     - use `__evict`, `__has`, `__split`, `__flag`, `__replace`
- `boundation-ordered`, `github-all`, `gtd`, `magnet-search`, `magnet-select`, `remove-duplicates`, `remove-part-extension`, `sbs-helper`, `config-sync`, `fix-downloads`, `fix-downloads-trackers`:
     - `mapfile` => `__split`
- `boundation-upgrade`, `discourse`, `sbs-helper`:
     - better safety
- add `generate-subtitles`:
     - uses openai whisper to generate subtitles for media that doesn't have them
- `remove-duplicates`:
     - use `is-same`
- remove `setup-util-bash-versions` is is now mainlined into dorothy core
- update and add various experiments
- `fix-download`, `fs-downloads`, `symlink-database`:
     - use `fs-path`
- `fix-download`:
     - fix broken `echo-escape-special` call
- `symlink-database`:
     - use `fs-link`
- `environment.bash`:
     - use native caching now that it is inside dorothy core
-

diff --git a/commands/discourse b/commands/discourse
--- a/commands/discourse
+++ b/commands/discourse
@@ -93,13 +93,12 @@ GIT_BRANCH='$option_git_branch'
 CONTAINER='$option_container'
 $(<"$DOROTHY/user/commands/discourse-setup")
 "
-	(ssh -t "$option_ssh_ip" "$discourse_init" && {
-		echo-style --success='Successfully setup the discourse instance. 🎉'
+	if ssh -t "$option_ssh_ip" "$discourse_init" && echo-style --success='Successfully setup the discourse instance. 🎉'; then
 		return 0
-	}) || {
-		echo-style --stderr --error='Error: Failed to setup the discourse instance. 🚨'
+	else
+		echo-style --stderr --error='Error: Failed to setup the discourse instance. 🚨' || return
 		return 1
-	}
+	fi
 )
 
 # fire if invoked standalone
