fix-permissions lint fix

diff --git a/commands/fix-permissions b/commands/fix-permissions
--- a/commands/fix-permissions
+++ b/commands/fix-permissions
@@ -16,7 +16,7 @@ if test -z "${group-}"; then
 fi
 
 function act {
-	sudo -H -u "$user" "$@" || sudo "$@" || echo "failed to run: $@"
+	sudo -H -u "$user" "$@" || sudo "$@" || echo "failed to run: $*"
 	echo
 }
 
